services:
  web:
    build: .
    container_name: php-web
    volumes:
      - ./public:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monsite
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db_data:
